from typing import Any

FormRecord = dict[str, Any]


FORMS: list[FormRecord] = [
    {
        "id": "form-client-001",
        "owner_type": "client",
        "owner_id": "client-101",
        "form_name": "Initial Care Assessment",
        "form_category": "Care Assessment",
        "status": "completed",
        "completed_date": "2026-01-15",
        "is_fixed": True,
        "responses_json": {
            "mobility": "Uses a walker and needs standby assistance.",
            "fall_risk": "Moderate",
            "medications": ["Lisinopril", "Metformin"],
            "care_needs": ["Meal preparation", "Vital checks"],
            "important_notes": "Prefers morning visits.",
        },
    },
    {
        "id": "form-client-002",
        "owner_type": "client",
        "owner_id": "client-101",
        "form_name": "Quarterly Care Assessment",
        "form_category": "Care Assessment",
        "status": "completed",
        "completed_date": "2026-04-18",
        "is_fixed": True,
        "responses_json": {
            "mobility": "Walks with a walker for up to 300 feet with assistance.",
            "fall_risk": "Low",
            "medications": ["Lisinopril", "Metformin", "Vitamin D"],
            "care_needs": ["Meal preparation", "Weekly vital checks"],
            "important_notes": "Mobility endurance has improved.",
        },
    },
    {
        "id": "form-client-003",
        "owner_type": "client",
        "owner_id": "client-101",
        "form_name": "Medication Check-In",
        "form_category": "Medication Review",
        "status": "completed",
        "completed_date": "2026-05-22",
        "is_fixed": False,
        "responses_json": {
            "Are medications taken as scheduled?": "Yes",
            "Any reported side effects?": "No",
            "Who organizes the pill box?": "Family caregiver",
        },
    },
    {
        "id": "form-client-004",
        "owner_type": "client",
        "owner_id": "client-101",
        "form_name": "June Wellness Check",
        "form_category": "Wellness Check",
        "status": "in_progress",
        "completed_date": None,
        "is_fixed": False,
        "responses_json": {
            "Current appetite": "Stable",
        },
    },
    {
        "id": "form-prospect-001",
        "owner_type": "prospective_client",
        "owner_id": "prospect-201",
        "form_name": "Service Inquiry",
        "form_category": "Intake",
        "status": "completed",
        "completed_date": "2026-03-10",
        "is_fixed": False,
        "responses_json": {
            "Requested services": "Companionship and transportation",
            "Preferred start date": "2026-04-01",
            "Preferred schedule": "Weekday afternoons",
        },
    },
    {
        "id": "form-caregiver-001",
        "owner_type": "caregiver",
        "owner_id": "caregiver-101",
        "form_name": "Annual Skills Review",
        "form_category": "Skills Review",
        "status": "completed",
        "completed_date": "2026-02-12",
        "is_fixed": True,
        "responses_json": {
            "certifications": ["CPR", "First Aid"],
            "skills": ["Dementia care", "Mobility assistance"],
            "restriction": "No lifting over 40 lb",
            "review_result": "Meets expectations",
        },
    },
    {
        "id": "form-caregiver-002",
        "owner_type": "caregiver",
        "owner_id": "caregiver-101",
        "form_name": "Supervision Feedback",
        "form_category": "Performance Review",
        "status": "completed",
        "completed_date": "2026-05-30",
        "is_fixed": False,
        "responses_json": {
            "Attendance": "Reliable",
            "Communication": "Clear and timely",
            "Development goal": "Complete advanced dementia training",
        },
    },
    {
        "id": "form-applicant-001",
        "owner_type": "applicant",
        "owner_id": "applicant-301",
        "form_name": "Employment Application",
        "form_category": "Application",
        "status": "completed",
        "completed_date": "2026-06-02",
        "is_fixed": True,
        "responses_json": {
            "role_applied_for": "Home Health Aide",
            "years_experience": 4,
            "availability": "Weekdays and alternating weekends",
            "has_transportation": True,
        },
    },
    {
        "id": "form-applicant-002",
        "owner_type": "applicant",
        "owner_id": "applicant-301",
        "form_name": "Reference Check",
        "form_category": "Screening",
        "status": "in_progress",
        "completed_date": None,
        "is_fixed": False,
        "responses_json": {
            "References contacted": "One of two",
        },
    },
]
